AWSTemplateFormatVersion: "2010-09-09"
Description: ECS/Fargate networking placeholder

Resources:

  FargateSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: ECS Fargate tasks security group
      VpcId: !Ref VpcId

Parameters:

  VpcId:
    Type: String

Outputs:

  FargateSecurityGroupId:
    Value: !Ref FargateSecurityGroup